# Generated by Django 4.2.4 on 2023-08-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osa_gpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя клиента')),
                ('phone_number', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('description', models.TextField(max_length=1000, verbose_name='описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osa_gpt.botuser', verbose_name='юзер бота')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-id'],
            },
        ),
    ]
