# Generated by Django 4.2.4 on 2023-08-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_gpt', '0002_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст чанка')),
                ('embedding', models.TextField(verbose_name='эмбеддинги')),
            ],
            options={
                'verbose_name': 'чанк базы знаний',
                'verbose_name_plural': 'чанки базы знаний',
                'ordering': ['-id'],
            },
        ),
    ]
