# Generated by Django 4.2.4 on 2023-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_gpt', '0003_knowledgebasechunks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptsAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='название промпта')),
                ('prompt', models.TextField(verbose_name='промпт')),
            ],
            options={
                'verbose_name': 'промпт',
                'verbose_name_plural': 'промпты',
                'ordering': ['-id'],
            },
        ),
    ]
